language: node_js
node_js:
 - '5.1'
 - '4.2'
 - '4.1'
 - '4.0'
services:
  - mongodb
cache:
    directories:
        - node_modules
env:
  matrix:
   - NODE_ENV=development
   - NODE_ENV=production
before_install: 
  - npm install babel-preset-react 
  - npm install babel-register
  - npm install babel-preset-es2015 
  - npm install react-addons-test-utils@0.14.7
  - npm install istanbul
  - npm install coveralls
  - npm install mocha
  - npm install chai
  - npm install jsdom
  - npm install supertest
  - npm install eslint
  - npm install eslint-config-airbnb
  - npm install eslint-plugin-react
script: npm run coverage
after_success:
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js