language: node_js
node_js:
 - '4.1'
 - '4.0'
 - '0.12'
 - '0.11'
 - '0.10'
env:
  matrix:
   - NODE_ENV=development
   - NODE_ENV=production
before_install: npm install --only=dev
script: npm run coverage
after_success:
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js