language: node_js
node_js:
 - '4.1'
 - '4.0'
#  - '0.12'
#  - '0.11'
#  - '0.10'
services:
  - mongodb
env:
  matrix:
   - NODE_ENV=development
   - NODE_ENV=production
before_install: 
  - npm install jest-cli 
  - npm install babel-jest 
  - npm install babel-preset-react 
  - npm install babel-preset-es2015 
  - npm install react-addons-test-utils 
  - npm install istanbul
  - npm install coveralls
  - npm install mocha
  - npm install chai
  - npm install jsdom
  - npm install supertest
  
script: npm run coverage
after_success:
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js